<?xml version="1.0" encoding="UTF-8" standalone="yes"?><!DOCTYPE catalog [<!ELEMENT catalog (book)*><!ELEMENT book (isbn|author|title|genre|price|publish_date|publisher)*><!ELEMENT isbn (#PCDATA)><!ELEMENT author (#PCDATA)><!ELEMENT title (#PCDATA)><!ELEMENT genre (#PCDATA)><!ELEMENT price (#PCDATA)><!ATTLIST price currency CDATA #IMPLIED><!ELEMENT publish_date (#PCDATA)><!ELEMENT publisher (#PCDATA)>]><catalog><book><isbn>978-0-1338-5904-1</isbn><author>Thomas Erl</author><title>Next Generation SOA</title><genre>Computer</genre><price>11.99</price><publish_date>2014-10-31T01:17:22.239+03:00</publish_date><publisher>Prentice Hall</publisher></book><book><isbn>978-1-4302-6827-7</isbn><author>Josh Juneau</author><title>Java 8 Recipes</title><genre>Computer</genre><price currency="USD">50.07</price><publish_date>2014-10-16T11:16:41.128+03:00</publish_date><publisher>Apress</publisher></book><book><isbn>978-1-78847-448-1</isbn><author>Enrico Pirozzi</author><title>PostgreSQL 10 High Performance</title><genre>Computer</genre><price currency="USD">45.16</price><publish_date>2018-04-16T13:26:31.178+03:00</publish_date><publisher>Packt</publisher></book></catalog>